# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-06-04 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstallTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_url', models.CharField(max_length=500)),
                ('auth_token', models.CharField(max_length=500)),
                ('install_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('uninstall_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('db_purge', models.CharField(default='-', max_length=500)),
                ('uninstaller_email', models.CharField(default='-', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ShopDeatz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_url', models.CharField(max_length=500)),
                ('auth_token', models.CharField(max_length=500)),
                ('initial_import', models.BooleanField(default=False)),
                ('last_import_datetime', models.DateTimeField(blank=True, default=None, null=True)),
                ('download_key', models.CharField(max_length=500)),
                ('charge_id', models.CharField(max_length=500)),
                ('shop_name', models.CharField(max_length=500)),
                ('total_exports', models.IntegerField(default=0)),
                ('last_exportdatetime', models.DateTimeField(blank=True, default=None, null=True)),
                ('last_partner_change_datetime', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
    ]
