# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-06-04 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModalCustomizations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_url', models.CharField(max_length=300)),
                ('active_template', models.CharField(max_length=100)),
                ('background_color', models.CharField(max_length=100)),
                ('text_color', models.CharField(max_length=100)),
                ('secondary_text_color', models.CharField(max_length=100)),
                ('active_tab_text_color', models.CharField(max_length=100)),
                ('accept_color', models.CharField(max_length=100)),
                ('decline_color', models.CharField(max_length=100)),
                ('font_type', models.CharField(max_length=100)),
                ('font_size', models.CharField(max_length=100)),
                ('time_delay', models.IntegerField(default=0)),
                ('widget_behaviour', models.CharField(default='Default', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TemplateDefaults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=100)),
                ('background_color', models.CharField(max_length=100)),
                ('text_color', models.CharField(max_length=100)),
                ('secondary_text_color', models.CharField(max_length=100)),
                ('active_tab_text_color', models.CharField(max_length=100)),
                ('accept_color', models.CharField(max_length=100)),
                ('decline_color', models.CharField(max_length=100)),
                ('font_type', models.CharField(max_length=100)),
                ('font_size', models.CharField(max_length=100)),
                ('time_delay', models.IntegerField(default=0)),
                ('widget_behaviour', models.CharField(default='Default', max_length=100)),
            ],
        ),
    ]
